### PR TITLE
Update WitchlingGadgets.zs

### PR DESCRIPTION
**Pull request by lilmoefow**
WHY IS THIS FILE CALLED WITCHLING GADGETS???  and I'm not sure those two original lines were doing anything? I could be wrong though.  

Don't merge yet, want to ask you a few more things first.

### CODE REVIEW

**Comment by Dominance** [comment]
Why are you adding back in the ability to use the WG blast furnace to produce steel? Transmuting by hand is yes a way to bypass GT of which I would remove myself but at least it's a pure time sink pain in the ass. This allows magic automate steel for cheap and bypass the early tech game.

**Comment by lilmoefow** [comment]
Those 2 lines Never prevented that blast furnace from Producing steel? If you want the Blast Furnace to not produce steel that can be added in.   With your 2 lines the plast furnace would still produce IC2's Reinfored Iron which auto oredicts to Gregtech Steel.

**Comment by spacebuilder2020** [comment]
Frankly. I don't think the player should be punished if they wish to invest in magic.   I do think there should be recipe changes so the steel recipe matches the gregtech one more.  Perhaps only working if the blast furnace has a supply of ignis, etc.   But these recipes should still exist but in a gregified manner.

**Comment by lilmoefow** [comment]
How about using Wrought Iron in the Infernal Blast Furnace to Produce Steel??

**Comment by Dominance** [comment]
Greging the recipes is a good way. I don't think there was many methods available when I first wrote the script. Not sure if this can produce aluminum or not but if it does it needs to be gated as well

**Comment by spacebuilder2020** [comment]
Yep.
:)

**Comment by spacebuilder2020** [comment]
And I think it can with native aluminum clusters.

**Comment by lilmoefow** [comment]
The Native clusters can only be made with Aluminum that is found on the moon that has the oredict tag of ore:oreAluminum    

Gregtechs aluminium is tagged  ore:oreAluminium  which will not turn into clusters.   This final change here should hopefully suit everyones likings.

**Comment by spacebuilder2020** [comment]
looks good

**Pull request merged**
